NAME: "RN50x4"
MODEL:
  EMBEDDING:
    EMBED_HEAD: 'two_stream'
  VISUAL_MODEL: 'RN50x4'
  TEXTUAL_MODEL: 'RN50x4'
LOSS:
  BCL_ALPHA: 0.6
  BCL_SCALE_ALPHA: 7
  BCL_BETA: 0.4
  BCL_SCALE_BETA: 40
  BCL_GAMA: 0.45
  BCL_SCALE_GAMA: 2
  MARGIN_LOSS_POS_MARGIN: 0.15
  MARGIN_LOSS_SM_MARGIN: 0.05
  MARGIN_LOSS_SCALE: 1.
  MARGIN_LOSS_SM_SCALE: 2.
  LOSSES: ('BCL', 'id_loss', 'HSMLM', 'HSMLD', 'BCL_mod', 'HSMLM_mod', 'HSMLD_mod')
DATALOADER:
  SAMPLER: 'identity'
  IMS_PER_ID: 4
  MOD_PERCENT_PER_SEN: 0.6
  MASK_PROB_PER_SEN: 0.4
  DROP_PROB_PER_SEN: 0.4
  TEXT_ENCODE_TYPE: 'mask_drop_nouns_adjs_verb_replace_v5'
PATH:
  DATASETS: ./datasets
  OUTPUTS: ./output
  PRE_TRAINED: ./pretrained/clip
DATASETS:
  NAME: 'CUHK-PEDES'
  VAL: 'test'
SOLVER:
  IMS_PER_BATCH: 128
  NUM_EPOCHS: 60
  CHECKPOINT_EPOCH: ()
  INIT_FACTOR: 5.0
TEST:
  IMS_PER_BATCH: 512